defaults:
  - override hydra/job_logging: none

seed: 42

benchmark:
  type: "till_steps" # ['till_time', 'till_reward', 'till_steps']
  till_time: 600 # seconds
  till_reward: 0 # float > 0
  for_steps: 30 # int > 0
  wandb:
    active: true
    project: "inference-diffusion-noise-optim"
  save_images:
    active: false
    save_dir: "./benchmark_runs"

dataset:
  name: "drawbench" # [drawbench, custom]
  cache_dir: "/scratch/gilbreth/pjajal/hf_datasets"
  prompts:
    - A bustling manga street, devoid of vehicles, detailed with vibrant colors and dynamic line work, characters in the background adding life and movement, under a soft golden hour light, with rich textures and a lively atmosphere, high resolution, sharp focus
    - Alice in a vibrant, dreamlike digital painting inside the Nemo Nautilus submarine.

pipeline:
  type: "sd" # ["sdxl", "sd3", "lcm", "pixart-sigma", "pixart-alpha"]
  model_id: "stable-diffusion-v1-5/stable-diffusion-v1-5"
  height: 512
  width: 512
  num_inference_steps: 50
  classifier_free_guidance: true
  guidance_scale: 7.5
  device_map: null
  dtype: "float16"
  cache_dir: null
  xformers_mem_eff_attn: false
  cpu_offload: false
  quantize: false
  device: "cuda"
  quantize_cfg:
    bits: "4bit" # ["4bit", "8bit"]

fitness:
  objective: "max" # ["max", "min"]
  device: "cuda"
  dtype: "float16"
  cache_dir: null
  problem_splits: 4
  fns:
    brightness:
      weight: 1.0
      active: false
    relative_luminance:
      weight: 1.0
      active: false
    jpeg_compressibility:
      weight: 1.0
      active: false
    clip:
      weight: 0.1
      active: false
      prompt: null
      model_name: "openai/clip-vit-base-patch32"
    aesthetic:
      weight: 1.0
      active: false
    pick:
      weight: 1.0
      active: false
      prompt: null
    novelty:
      weight: 0.05
      active: false
      model_name: "dino_base"
      top_k: 15
    hpsv2:
      weight: 1.0
      active: false
    imagereward:
      active: true
      weight: 1.0

noise_injection:
  type: "noise" # ["rotational_transform", "svd_rot_transform", "noise"]
  add_noise: false
  mean_scale: 0.01
  bound: 0.1

solver:
  algorithm: "snes" # ["cmaes" , "snes", "ga", "cosyne"]
  initial_bounds: [-1, 1]
  initialization:
    mean: 0.0
    std: 1.0
  cmaes:
    stdev_init: 0.1
    separable: true
    center_init: "latents" # null | ["latents"]
    csa_squared: true
    popsize: null
  snes:
    radius_init: 40
    center_learning_rate: 1.0
    optimizer: "clipup" # ["adam", "clipup", "null"]
    center_init: "latents" # null | ["latents"]
    popsize: null
  pgpe:
    popsize: 16
    center_init: null # null | ["latents"]
    center_learning_rate: 40
    stdev_learning_rate: 10
    stdev_init: 1.0
    radius_init: null
  cosyne:
    popsize: 16
    tournament_size: 2
    mutation_probability: 1.0
    mutation_stdev: 0.10
    permute_all: true
    elitism_ratio: 0.01
    eta: null