defaults:
  - override hydra/job_logging: none

seed: 32132

benchmark:
  type: "till_steps" # ['till_time', 'till_reward', 'till_steps']
  till_time: 600 # seconds
  till_reward: 0 # float > 0
  for_steps: 30 # int > 0
  wandb:
    active: true
    project: "inference-diffusion-noise-optim"
  save_images:
    active: true
    save_dir: "./benchmark_runs"

dataset:
  name: "drawbench" # [drawbench, custom]
  cache_dir: "/scratch/gilbreth/pjajal/hf_datasets"
  prompts:
    - "Closeup portrait of an ancient evil wizard with dramatic light, ethereal lake background, intricate runes, and mystical symbols, painted in a fantasy style"
    # - "the Kremlin, digital art, painterly brushstrokes, vibrant color palette, dynamic composition, dramatic chiaroscuro, high resolution, sharp focus"
    # - "Sydney Opera House, anime style, colorful, dynamic angles, detailed, bustling city, lively characters, exaggerated expressions, manga details"
    # - "a bustling kitchen, vibrant color palette, dynamic anime style, Studio Ghibli aesthetics, detailed character interactions, warm golden hour light, playful exaggeration, high resolution, rich textures"
    # - "8-bit movie poster for Mad Max with older Mel Gibson and younger female companion, pixelated title text, vibrant retro colors, blocky characters, and a pixel-perfect wasteland backdrop, dynamic perspective, high resolution, sharp focus, dramatic chiaroscuro lighting, energetic atmosphere"
    # - A bustling manga street, devoid of vehicles, detailed with vibrant colors and dynamic line work, characters in the background adding life and movement, under a soft golden hour light, with rich textures and a lively atmosphere, high resolution, sharp focus

pipeline:
  type: "sd3" # ["sdxl", "sd3"]
  model_id: "stabilityai/stable-diffusion-3.5-medium"
  height: 512
  width: 512
  num_inference_steps: 28
  classifier_free_guidance: true
  guidance_scale: 4.5
  device_map: null
  dtype: "float16"
  cache_dir: null
  xformers_mem_eff_attn: true
  cpu_offload: true
  quantize: false
  device: "cuda"
  quantize_cfg:
    bits: "4bit" # ["4bit", "8bit"]

fitness:
  objective: "max" # ["max", "min"]
  device: "cuda"
  dtype: "float16"
  cache_dir: null
  problem_splits: 2
  fns:
    brightness:
      weight: 1.0
      active: false
    relative_luminance:
      weight: 1.0
      active: false
    jpeg_compressibility:
      weight: 1.0
      active: false
    clip:
      weight: 1.0
      active: false
      prompt: null
      model_name: "openai/clip-vit-base-patch16"
    aesthetic:
      weight: 1.0
      active: false
    pick:
      weight: 1.0
      active: false
      prompt: null
    novelty:
      weight: 0.05
      active: false
      model_name: "dino_base"
      top_k: 15
    hpsv2:
      active: false
      weight: 1.0
    imagereward:
      active: true
      weight: 1.0

noise_injection:
  type: "noise" # ["rotational_transform", "svd_rot_transform", "noise", "multi_axis_rot"]
  add_noise: false
  mean_scale: 0.0001
  bound: 0.1

solver:
  algorithm: "cosyne" # ["cmaes" , "snes", "ga", "cosyne"]
  initial_bounds: [-1, 1]
  initialization:
    mean: 0.0
    std: 1.0
  cmaes:
    stdev_init: 0.1
    separable: true
    center_init: null # null | ["latents"]
    csa_squared: true
  snes:
    radius_init: 50
    center_learning_rate: 3
    optimizer: "clipup" # ["adam", "clipup", "null"]
    center_init: "latents" # null | ["latents"]
    popsize: 16
  pgpe:
    popsize: 16
    center_init: "latents" # null | ["latents"]
    center_learning_rate: 3
    stdev_learning_rate: 1
    stdev_init: 1.0
    radius_init: null 
  cosyne:
    popsize: 16
    tournament_size: 2
    mutation_probability: 1.0
    mutation_stdev: 0.10
    permute_all: true
    elitism_ratio: 0.01
    eta: null